In [1]:
# import bq_helper package
import bq_helper

In [2]:
# create a helper object for bigquery dataset
hacker_news = bq_helper.BigQueryHelper(active_project= "bigquery-public-data", 
                                       dataset_name = "hacker_news")

Using Kaggle's public dataset BigQuery integration.

In [3]:
# print a list of all the tables in the hacker_news dataset
hacker_news.list_tables()

['comments', 'full', 'full_201510', 'stories']

In [4]:
# print information on all the columns in the "full" table
# in the hacker_news dataset
hacker_news.table_schema("full")

,name,type,mode,description
0,title,STRING,NULLABLE,Story title
1,url,STRING,NULLABLE,Story url
2,text,STRING,NULLABLE,Story or comment text
3,dead,BOOLEAN,NULLABLE,Is dead?
4,by,STRING,NULLABLE,The username of the item's author.
5,score,INTEGER,NULLABLE,Story score
6,time,INTEGER,NULLABLE,Unix time
7,timestamp,TIMESTAMP,NULLABLE,Timestamp for the unix time
8,type,STRING,NULLABLE,"Type of details (comment, comment_ranking, pol..."
9,id,INTEGER,NULLABLE,The item's unique id.
10,parent,INTEGER,NULLABLE,Parent comment ID
11,descendants,INTEGER,NULLABLE,Number of story or poll descendants
12,ranking,INTEGER,NULLABLE,Comment ranking
13,deleted,BOOLEAN,NULLABLE,Is deleted?

In [5]:
# print information on all the columns in the "comments" table
hacker_news.table_schema("comments")

,name,type,mode,description
0,id,INTEGER,NULLABLE,Unique comment ID
1,by,STRING,NULLABLE,Username of commenter
2,author,STRING,NULLABLE,Username of author
3,time,INTEGER,NULLABLE,Unix time
4,time_ts,TIMESTAMP,NULLABLE,Human readable time in UTC (format: YYYY-MM-DD...
5,text,STRING,NULLABLE,Comment text
6,parent,INTEGER,NULLABLE,Parent comment ID
7,deleted,BOOLEAN,NULLABLE,Is deleted?
8,dead,BOOLEAN,NULLABLE,Is dead?
9,ranking,INTEGER,NULLABLE,Comment ranking

In [6]:
# print information on all the columns in the "stories" table
hacker_news.table_schema("stories")

,name,type,mode,description
0,id,INTEGER,NULLABLE,Unique story ID
1,by,STRING,NULLABLE,Username of submitter
2,score,INTEGER,NULLABLE,Story score
3,time,INTEGER,NULLABLE,Unix time
4,time_ts,TIMESTAMP,NULLABLE,Human readable time in UTC (format: YYYY-MM-DD...
5,title,STRING,NULLABLE,Story title
6,url,STRING,NULLABLE,Story url
7,text,STRING,NULLABLE,Story text
8,deleted,BOOLEAN,NULLABLE,Is deleted?
9,dead,BOOLEAN,NULLABLE,Is dead?
10,descendants,INTEGER,NULLABLE,Number of story descendants
11,author,STRING,NULLABLE,Username of author

In [7]:
# preview the first couple lines of the "full" table
hacker_news.head("full")

,title,url,text,dead,by,score,time,timestamp,type,id,parent,descendants,ranking,deleted
0,None,None,"I did this yesterday as well, Aegis seems real...",None,cknight,None,1661649539,2022-08-28 01:18:59+00:00,comment,32624836,32623553,None,None,None
1,None,None,"My point still stands: to fix this, you have t...",None,flyinRyan,None,1367242150,2013-04-29 13:29:10+00:00,comment,5625969,5625463,None,None,None
2,None,None,I&#x27;m glad they talk a good bit about perce...,None,giantg2,None,1648475308,2022-03-28 13:48:28+00:00,comment,30830439,30829243,None,None,None
3,None,None,Geography is not the reason why it&#x27;s been...,None,0xbadcafebee,None,1660084945,2022-08-09 22:42:25+00:00,comment,32405509,32403575,None,None,None
4,None,None,What I found most interesting was the sum conv...,None,uoaei,None,1648475304,2022-03-28 13:48:24+00:00,comment,30830438,30811979,None,None,None

In [8]:
# preview the first couple lines of the "comments" table
hacker_news.head("comments")

,id,by,author,time,time_ts,text,parent,deleted,dead,ranking
0,9734136,None,None,1434565400,2015-06-17 18:23:20+00:00,None,9733698,True,None,0
1,4921158,None,None,1355496966,2012-12-14 14:56:06+00:00,None,4921100,True,None,0
2,7500568,None,None,1396261158,2014-03-31 10:19:18+00:00,None,7499385,True,None,0
3,8909635,None,None,1421627275,2015-01-19 00:27:55+00:00,None,8901135,True,None,0
4,9256463,None,None,1427204705,2015-03-24 13:45:05+00:00,None,9256346,True,None,0

In [9]:
# preview the first couple lines of the "stories" table
hacker_news.head("stories")

,id,by,score,time,time_ts,title,url,text,deleted,dead,descendants,author
0,6988445,cflick,0,1388454902,2013-12-31 01:55:02+00:00,Appshare,http://chadflick.ws/appshare.html,Did facebook or angrybirds pay you? We will!,None,True,None,cflick
1,7047571,Rd2,1,1389562985,2014-01-12 21:43:05+00:00,Java in startups,,"Hello, hacker news!<p>Have any of you used jav...",None,True,None,Rd2
2,9157712,mo0,1,1425657937,2015-03-06 16:05:37+00:00,Show HN: Discover what songs were used in YouT...,http://www.mooma.sh/,The user can paste a media url(currently only ...,None,True,None,mo0
3,8127403,ad11,1,1407052667,2014-08-03 07:57:47+00:00,"My poker project, what do you think?",,"Hi guys, what do you think about my poker proj...",None,True,None,ad11
4,6933158,emyy,1,1387432701,2013-12-19 05:58:21+00:00,Christmas Crafts Ideas - Easy and Simple Famil...,http://www.winxdvd.com/resource/christmas-craf...,There are some free Christmas craft ideas to m...,None,True,None,emyy

In [10]:
# preview the first 10 entries in the 'by' column of the full table
hacker_news.head("full", selected_columns="by", num_rows=10)

              by
0        cknight
1      flyinRyan
2        giantg2
3   0xbadcafebee
4          uoaei
5       mambodog
6   metamemetics
7    mhausenblas
8       mambodog
9  dsplittgerber

In [11]:
# preview the first 10 entries in the 'title' column of the stories table
hacker_news.head("stories", selected_columns=["title","text","url"], num_rows=10)

,title,url,text
0,Appshare,http://chadflick.ws/appshare.html,Did facebook or angrybirds pay you? We will!
1,Java in startups,,"Hello, hacker news!<p>Have any of you used jav..."
2,Show HN: Discover what songs were used in YouT...,http://www.mooma.sh/,The user can paste a media url(currently only ...
3,"My poker project, what do you think?",,"Hi guys, what do you think about my poker proj..."
4,Christmas Crafts Ideas - Easy and Simple Famil...,http://www.winxdvd.com/resource/christmas-craf...,There are some free Christmas craft ideas to m...
5,Should an engineer go deeper or broader?,,"Generally speaking, should an engineer try to ..."
6,"Tell HN: Friendly reminder, if on Sat you're c...",,instead of working on your startup&#x2F;idea 6...
7,Great time tracker SalaryBook for iPad turned ...,http://bit.ly/WvOSXC,"Freelancers, consultants, and professionals ca..."
8,Can someone recommend a good web hosting site,,SO my friend got asked to find a good free web...
9,Why is fish oil good for your eyes?,http://www.globallaservision.com/blog/fish-oil...,You have questions? We have the answers. Healt...

In [12]:
# this query looks in the full table in the hacker_news
# dataset, then gets the score column from every row where 
# the type column has "job" in it.
query1 = """SELECT score
            FROM `bigquery-public-data.hacker_news.full`
            WHERE type = "job" """

# check how big this query will be
hacker_news.estimate_query_size(query1)

0.3021250478923321

In [13]:
# this query looks in the full table in the hacker_news
# dataset, then gets the score column from every row where 
# the type column has "job" in it.
query = """SELECT text
            FROM `bigquery-public-data.hacker_news.stories`
            WHERE title = "Appshare" """

# check how big this query will be
hacker_news.estimate_query_size(query)

0.16961119882762432

In [14]:
# only run this query if it's less than 100 MB
hacker_news.query_to_pandas_safe(query1, max_gb_scanned=0.1)

Query cancelled; estimated size of 0.3021250478923321 exceeds limit of 0.1 GB

In [15]:
# only run this query if it's less than 100 MB
hacker_news.query_to_pandas_safe(query, max_gb_scanned=0.1)

Query cancelled; estimated size of 0.16961119882762432 exceeds limit of 0.1 GB